import type {
  Incident,
  IncidentAiReport,
  IncidentAuditTrail,
  IncidentTask,
  Prisma,
} from "@prisma/client";

import type {
  ChecklistItem,
  PostmortemReport,
  RiskClassification,
  TechnicalActionPlan,
  TimelineEntry,
} from "@/modules/reports/report.types";

export type MarkdownExportIncident = Incident & {
  aiReport: IncidentAiReport | null;
  tasks: IncidentTask[];
  auditTrails: IncidentAuditTrail[];
};

export function generateIncidentMarkdownReport(
  incident: MarkdownExportIncident,
): string {
  const report = normalizeReport(incident.aiReport);

  return [
    "# Incident Post-Mortem Report",
    renderIncidentOverview(incident),
    renderImpactSummary(incident),
    renderSuspectedCause(incident),
    renderRiskClassification(report.riskClassification),
    renderTimeline(report.timeline, incident),
    renderChecklist(report.checklist),
    renderTechnicalActionPlan(report.technicalActionPlan),
    renderStakeholderSummary(report.stakeholderSummary),
    renderPostmortemReport(report.postmortemReport),
    renderTasks(incident.tasks),
    renderAuditTrail(incident.auditTrails),
    "Generated by ReguAI - Incident Response & Compliance Workflow Platform.",
  ].join("\n\n");
}

function renderIncidentOverview(incident: MarkdownExportIncident): string {
  return [
    "## Incident Overview",
    `- Incident ID: ${escapeMarkdown(incident.id)}`,
    `- Title: ${escapeMarkdown(incident.title)}`,
    `- Type: ${escapeMarkdown(incident.type)}`,
    `- Severity: ${incident.severity}`,
    `- Status: ${incident.status}`,
    `- Affected System: ${escapeMarkdown(incident.affectedSystem)}`,
    `- Affected Users: ${incident.affectedUsers}`,
    `- Detected At: ${formatDate(incident.detectedAt)}`,
    `- Resolved At: ${formatNullableDate(incident.resolvedAt)}`,
  ].join("\n");
}

function renderImpactSummary(incident: MarkdownExportIncident): string {
  return ["## Impact Summary", escapeMarkdown(incident.impactSummary)].join("\n\n");
}

function renderSuspectedCause(incident: MarkdownExportIncident): string {
  return [
    "## Suspected Cause",
    escapeMarkdown(incident.suspectedCause ?? "No suspected cause recorded."),
  ].join("\n\n");
}

function renderRiskClassification(
  riskClassification: RiskClassification | null,
): string {
  if (!riskClassification) {
    return "## Risk Classification\n\nReport has not been generated yet.";
  }

  return [
    "## Risk Classification",
    `- Recommended Severity: ${riskClassification.recommendedSeverity}`,
    `- Category: ${riskClassification.category}`,
    `- Business Risk: ${escapeMarkdown(riskClassification.businessRisk)}`,
    `- Technical Risk: ${escapeMarkdown(riskClassification.technicalRisk)}`,
    `- Compliance Risk: ${escapeMarkdown(riskClassification.complianceRisk)}`,
    `- Recommended SLA: ${escapeMarkdown(riskClassification.recommendedSla)}`,
  ].join("\n");
}

function renderTimeline(
  timeline: TimelineEntry[] | null,
  incident: MarkdownExportIncident,
): string {
  if (timeline && timeline.length > 0) {
    return [
      "## Timeline",
      ...timeline.map(
        (entry) => `- ${escapeMarkdown(entry.time)} - ${escapeMarkdown(entry.event)}`,
      ),
    ].join("\n");
  }

  const fallbackTimeline = [
    `- Created At - ${formatDate(incident.createdAt)}`,
    `- Updated At - ${formatDate(incident.updatedAt)}`,
  ];

  if (incident.resolvedAt) {
    fallbackTimeline.push(`- Resolved At - ${formatDate(incident.resolvedAt)}`);
  }

  return ["## Timeline", ...fallbackTimeline].join("\n");
}

function renderChecklist(checklist: ChecklistItem[] | null): string {
  if (!checklist || checklist.length === 0) {
    return "## Response Checklist\n\nNo generated checklist available.";
  }

  return [
    "## Response Checklist",
    ...checklist.map((item) => {
      const marker = item.done ? "x" : " ";
      return `- [${marker}] ${escapeMarkdown(item.title)}`;
    }),
  ].join("\n");
}

function renderTechnicalActionPlan(
  actionPlan: TechnicalActionPlan | null,
): string {
  if (!actionPlan) {
    return "## Technical Action Plan\n\nNo technical action plan available.";
  }

  const sections = [
    renderActionPlanGroup("Backend", actionPlan.backend),
    renderActionPlanGroup("Database", actionPlan.database),
    renderActionPlanGroup("QA", actionPlan.qa),
    renderActionPlanGroup("DevOps", actionPlan.devops),
    renderActionPlanGroup("Security", actionPlan.security),
    renderActionPlanGroup("Compliance", actionPlan.compliance),
  ].filter((section) => section.length > 0);

  if (sections.length === 0) {
    return "## Technical Action Plan\n\nNo technical action plan available.";
  }

  return ["## Technical Action Plan", ...sections].join("\n\n");
}

function renderStakeholderSummary(summary: string | null): string {
  return [
    "## Stakeholder Summary",
    escapeMarkdown(summary ?? "No stakeholder summary available."),
  ].join("\n\n");
}

function renderPostmortemReport(postmortem: PostmortemReport | null): string {
  if (!postmortem) {
    return "## Post-Mortem Report\n\nPost-mortem report has not been generated yet.";
  }

  return [
    "## Post-Mortem Report",
    "### Executive Summary",
    escapeMarkdown(postmortem.executiveSummary),
    "### Incident Details",
    escapeMarkdown(postmortem.incidentDetails),
    "### Impact",
    escapeMarkdown(postmortem.impact),
    "### Root Cause",
    escapeMarkdown(postmortem.rootCause),
    "### Resolution",
    escapeMarkdown(postmortem.resolution),
    "### Prevention Plan",
    renderList(postmortem.preventionPlan),
    "### Action Items",
    renderList(postmortem.actionItems),
    "### Owners",
    renderList(postmortem.owners),
    "### Audit Notes",
    renderList(postmortem.auditNotes),
  ].join("\n\n");
}

function renderTasks(tasks: IncidentTask[]): string {
  if (tasks.length === 0) {
    return "## Tasks\n\nNo tasks created yet.";
  }

  return [
    "## Tasks",
    ...tasks.map((task) =>
      [
        `- Title: ${escapeMarkdown(task.title)}`,
        `  - Status: ${task.status}`,
        `  - Priority: ${task.priority}`,
        `  - Owner: ${escapeMarkdown(task.owner)}`,
        `  - Due Date: ${formatNullableDate(task.dueDate)}`,
      ].join("\n"),
    ),
  ].join("\n");
}

function renderAuditTrail(auditTrails: IncidentAuditTrail[]): string {
  if (auditTrails.length === 0) {
    return "## Audit Trail\n\nNo audit trail available.";
  }

  return [
    "## Audit Trail",
    ...auditTrails.map((auditTrail) =>
      [
        `- Created At: ${formatDate(auditTrail.createdAt)}`,
        `  - Action: ${escapeMarkdown(auditTrail.action)}`,
        `  - Actor: ${escapeMarkdown(auditTrail.actor)}`,
        `  - Note: ${escapeMarkdown(auditTrail.note ?? "No note")}`,
      ].join("\n"),
    ),
  ].join("\n");
}

function renderActionPlanGroup(title: string, items: string[]): string {
  if (items.length === 0) {
    return "";
  }

  return [`### ${title}`, renderList(items)].join("\n\n");
}

function renderList(items: string[]): string {
  if (items.length === 0) {
    return "- None";
  }

  return items.map((item) => `- ${escapeMarkdown(item)}`).join("\n");
}

function normalizeReport(report: IncidentAiReport | null): {
  riskClassification: RiskClassification | null;
  timeline: TimelineEntry[] | null;
  checklist: ChecklistItem[] | null;
  technicalActionPlan: TechnicalActionPlan | null;
  stakeholderSummary: string | null;
  postmortemReport: PostmortemReport | null;
} {
  if (!report) {
    return {
      riskClassification: null,
      timeline: null,
      checklist: null,
      technicalActionPlan: null,
      stakeholderSummary: null,
      postmortemReport: null,
    };
  }

  return {
    riskClassification: isRiskClassification(report.riskClassification)
      ? report.riskClassification
      : null,
    timeline: isTimeline(report.timeline) ? report.timeline : null,
    checklist: isChecklist(report.checklist) ? report.checklist : null,
    technicalActionPlan: isTechnicalActionPlan(report.technicalActionPlan)
      ? report.technicalActionPlan
      : null,
    stakeholderSummary: report.stakeholderSummary,
    postmortemReport: isPostmortemReport(report.postmortemReport)
      ? report.postmortemReport
      : null,
  };
}

function isRiskClassification(value: Prisma.JsonValue): value is RiskClassification {
  return (
    isRecord(value) &&
    typeof value.recommendedSeverity === "string" &&
    typeof value.category === "string" &&
    typeof value.businessRisk === "string" &&
    typeof value.technicalRisk === "string" &&
    typeof value.complianceRisk === "string" &&
    typeof value.recommendedSla === "string"
  );
}

function isTimeline(value: Prisma.JsonValue): value is TimelineEntry[] {
  return (
    Array.isArray(value) &&
    value.every(
      (entry) =>
        isRecord(entry) &&
        typeof entry.time === "string" &&
        typeof entry.event === "string",
    )
  );
}

function isChecklist(value: Prisma.JsonValue): value is ChecklistItem[] {
  return (
    Array.isArray(value) &&
    value.every(
      (item) =>
        isRecord(item) &&
        typeof item.title === "string" &&
        typeof item.done === "boolean" &&
        typeof item.category === "string",
    )
  );
}

function isTechnicalActionPlan(
  value: Prisma.JsonValue,
): value is TechnicalActionPlan {
  return (
    isRecord(value) &&
    isStringArray(value.backend) &&
    isStringArray(value.database) &&
    isStringArray(value.qa) &&
    isStringArray(value.devops) &&
    isStringArray(value.security) &&
    isStringArray(value.compliance)
  );
}

function isPostmortemReport(value: Prisma.JsonValue): value is PostmortemReport {
  return (
    isRecord(value) &&
    typeof value.executiveSummary === "string" &&
    typeof value.incidentDetails === "string" &&
    typeof value.impact === "string" &&
    typeof value.rootCause === "string" &&
    typeof value.resolution === "string" &&
    isStringArray(value.preventionPlan) &&
    isStringArray(value.actionItems) &&
    isStringArray(value.owners) &&
    isStringArray(value.auditNotes)
  );
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((item) => typeof item === "string");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function escapeMarkdown(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function formatDate(date: Date): string {
  return date.toISOString();
}

function formatNullableDate(date: Date | null): string {
  return date ? formatDate(date) : "N/A";
}
