"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar, Clock } from "lucide-react";

interface PostMortemSection {
  title: string;
  content: string;
}

interface PostMortemData {
  incidentTitle: string;
  severity: string;
  duration?: string;
  impactedUsers?: number;
  sections: PostMortemSection[];
  generatedAt?: string;
}

interface PostMortemPreviewProps {
  data?: PostMortemData;
  onDownload?: () => void;
  title?: string;
}

export function PostMortemPreview({
  data,
  onDownload,
  title = "Post-Mortem Report",
}: PostMortemPreviewProps) {
  if (!data) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>{title}</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-12">
            <FileText className="w-12 h-12 mx-auto mb-4 text-gray-400" />
            <p className="text-gray-500 mb-4">
              No post-mortem report available
            </p>
            <p className="text-sm text-gray-400">
              Generate a report once the incident is resolved
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="space-y-2">
            <CardTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5" />
              {title}
            </CardTitle>
            <p className="text-sm text-gray-600">{data.incidentTitle}</p>
          </div>
          {onDownload && (
            <Button onClick={onDownload} variant="outline" size="sm">
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
          )}
        </div>

        {/* Metadata */}
        <div className="flex flex-wrap items-center gap-4 pt-4 border-t mt-4">
          <Badge variant="destructive">{data.severity}</Badge>
          {data.duration && (
            <div className="flex items-center gap-1 text-sm text-gray-600">
              <Clock className="w-4 h-4" />
              <span>Duration: {data.duration}</span>
            </div>
          )}
          {data.impactedUsers !== undefined && (
            <div className="flex items-center gap-1 text-sm text-gray-600">
              <span>Impacted Users: {data.impactedUsers.toLocaleString()}</span>
            </div>
          )}
          {data.generatedAt && (
            <div className="flex items-center gap-1 text-sm text-gray-600">
              <Calendar className="w-4 h-4" />
              <span>
                Generated: {new Date(data.generatedAt).toLocaleDateString()}
              </span>
            </div>
          )}
        </div>
      </CardHeader>

      <CardContent>
        <div className="space-y-6">
          {data.sections.map((section, index) => (
            <div key={index} className="space-y-3">
              <h3 className="text-lg font-semibold text-gray-900 flex items-center gap-2">
                <span className="flex items-center justify-center w-6 h-6 rounded-full bg-primary/10 text-primary text-sm font-bold">
                  {index + 1}
                </span>
                {section.title}
              </h3>
              <div className="pl-8">
                <div className="prose prose-sm max-w-none">
                  <p className="text-gray-700 whitespace-pre-wrap leading-relaxed">
                    {section.content}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 pt-6 border-t">
          <div className="flex items-center justify-between text-sm text-gray-500">
            <p>This report was automatically generated by ReguAI</p>
            {data.generatedAt && (
              <p>{new Date(data.generatedAt).toLocaleString()}</p>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

// Made with Bob
